services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - /home/mdekker/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mariadb-admin ping -h localhost -u root -p"$${DB_ROOT_PASSWORD}" --silent',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - /home/mdekker/data/wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - /home/mdekker/data/wordpress:/var/www/html:ro
    depends_on:
      - wordpress
    restart: unless-stopped

networks:
  inception:
    driver: bridge
